### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by mikhirev** [aeharding/voyager#1228]
**Is your feature request related to a problem? Please describe.**
In other apps spellchecker is active in in put fields, but not in Voyager.

**Describe the solution you'd like**
Enable spell checking in post/comment form.

**Comment by aeharding** [comment]
Hi,

Spell checking works for me. Could you please attach a screenshot?

**Comment by mikhirev** [comment]
![Screenshot_20240210-203413](https://github.com/aeharding/voyager/assets/1032317/2dc95229-fcc2-47cb-b6b9-3aa7e7d45893)

IDK if this matters but my system language is not English. Spellchecker doesn't work for any language.

**Comment by aeharding** [comment]
Interesting, what is your android OS version?

**Comment by mikhirev** [comment]
> Interesting, what is your android OS version?

GrapheneOS (Android 13). The same on my old phone with Android 8.

**Comment by aeharding** [comment]
Thanks, this should hopefully be fixed in the next release of Voyager!

**Comment by mikhirev** [comment]
Just upgraded to 1.39.0 from f-droid but spellchecker still doesn't work.

**Comment by aeharding** [comment]
Hi!

It hasn't been released yet, but it will in the next version. Sorry for the delay.
