### ISSUE TITLE
After being minimized for too long app goes blank

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#946]
**Describe the bug**
After the app is being minimized for too long and it is reopened. The window comes back blank and the app becomes unusable.

**To Reproduce**
Minimize the app and use other apps for about 10 minutes.

**Expected behavior**
When the app is opened again, it should come back to the last place it was left on.

**Screenshots**
https://github.com/aeharding/voyager/assets/104597302/815367e1-ef0f-4008-8c19-2830edc38a43

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.1

**Comment by aeharding** [comment]
Hi, I have experienced a white screen loading the app in development, but I haven't in production yet.

Also, I am not able to reproduce with your reproduction steps. The app continues to work on my device. If you can determine a consistent reproduction let me know, otherwise I'll keep my eye out.

**Comment by aeharding** [comment]
@sallyFoster Are you running Test Flight, and are you still able to consistently reproduce? If so, can you do me a favor and install 1.23.0, check if you still have the problem, and then check 1.22.0 and see if the problem goes away?

Thanks!

**Comment by H6nry** [comment]
Not sure if it helps, but I think I can reliably reproduce similar symptoms in a different way. I've got an iPhone SE (2016) on iOS 14.7.1 and since TestFlight version 1.23.1 it permanently loads into the described blank screen right after installation. Reinstalling the app didn't help, but a downgrade to 1.22.1 fixed the bug in 2/2 tries. I haven't tested long time stability yet, though.

I think I can't build a voyager app on my "ancient" Mac, but if you need any debug logs I'd be glad to try.

**Comment by RocketRide9** [comment]
I got this issue several times in 1.23.3 and in 1.24.0 after I installed it in TrollStore and opened. Omw to test 1.22.

**Comment by fer0n** [comment]
I'm running the 1.23.2 (177) TestFlight version and I've been seeing the same issue. After being idle for some time, when I come back I get a completely black screen (dark mode). It happens quite often.

**Comment by sallyFoster** [comment]
@aeharding No, I am not using test flight. I am using the app store version.

**Comment by aeharding** [comment]
Thanks everyone for your help.

Because this issue appears to NOT be present in 1.22 and appeared in v1.23, I believe this is related to https://github.com/aeharding/voyager/pull/913, perhaps due to https://github.com/j3k0/cordova-plugin-purchase/issues/1483.

I have a fix in progress.

**Comment by aeharding** [comment]
Leaving this open until fix can be confirmed.

**Comment by RocketRide9** [comment]
i cant reproduce it in 1.24.2 on ios 15.3 iphone se

**Comment by aeharding** [comment]
Thanks @RocketRide9. I *think* this is resolved (update is in stores) but because it's so sporadic, please let me know if anyone encounters issues.

**Comment by H6nry** [comment]
iOS 14 iPhone SE (2016) and I couldn't reproduce it within one day of testing. (100 % reproduction rate before, so this is certainly an improvement on my side)

**Comment by sallyFoster** [comment]
@aeharding The blank screen is still happening in the case that the internet connection is lost and then the user reconnects using a VPN

https://github.com/aeharding/voyager/assets/104597302/7e8a9ff5-ad82-4381-8de8-e12d9c1cad7a
